View -> Control
View -> Window
View -> ViewContainerBase

Control -> Sheet
Window -> Screen
Window -> Modal
Window -> Activity

ViewContainerBase -> ControlContainerBase
ViewContainerBase -> WindowContainerBase

ControlContainerBase -> SimpleControlContainer
ControlContainerBase -> SheetContainer

WindowContainerBase -> ScreenContainer
WindowContainerBase -> ModalContainer
WindowContainerBase -> ActivityContainer
